### ISSUE TITLE
Error in = > doICA.m at line 73

### ISSUE THREAD

**Issue by pkfsantos** [LabBandSB/BIODICA#2]
Dear all,
I am not able to scan for a range of component number in the ICA analysis. I can run from 2 to 9, but when I choose to scan for 10 or more component number I get the error message:

Illegal value [10] for parameter: 'lastEig'
Error in => doICA.m at line 73

Someone could help me with this issue?
Thank you,
Priscila

**Comment by LabBandSB** [comment]
Dear Priscilla,

Thank you for your interest to BIODICA.

Usually this error revealing, when the number of desired components are
higher that the number of samples in your analized datasets. Usually, the
basic principle is following the formula "n-1".

Please check the number of your samples and the number of calculated ICs.

If you have any questions, please do not hesitate to contact me.

Kind regards,
Ulykbek and BIODICA team

ср, 1 мая 2019 г., 23:57 pkfsantos <notifications@github.com>:

**Comment by pkfsantos** [comment]
Thank you very much. I thought it was possible to test more ICs than the sample number.
